name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install chess

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Build distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload distribution to PyPI
      env:
        TWINE_API_TOKEN: ${{ pypi-AgEIcHlwaS5vcmcCJDMwNTQxODFkLTdkYjAtNDg0NS05ZGQyLTE5MDliMmQ0NTc4NgACKlszLCIwNzQwMWE2NS02NjQ5LTQzMzAtOTViMi0xYTg0ZjJiMWM3NTEiXQAABiBRCcMB--wc6-5RZ6ze8gHLrxWzQZJV0hSighT--u6LNA }}
      run: |
        python -m pip install --upgrade twine
        twine upload dist/*
